### ISSUE TITLE
Text runs out of hint dialog in level 4

### ISSUE THREAD

**Issue by jschwartzenberg** [yuv422/cosmo-engine#11]
![image](https://user-images.githubusercontent.com/877112/84600895-e9358d00-ae7c-11ea-948c-8e8cdb416948.png)

**Comment by yuv422** [comment]
ok I think I've fixed the layout on that hint dialog. I've noticed another issue though. The actor sprites aren't being drawn when the dialog is displayed. I'll take a look at that now.

**Comment by yuv422** [comment]
Ok I've also fixed the actor display issues while showing the hint dialog.

**Comment by jschwartzenberg** [comment]
Yeah all looks good now! Great!!
