### ISSUE TITLE
add scaling support

### ISSUE THREAD

**Issue by Askmewho** [yuv422/cosmo-engine#17]
HI! tested on linux! niceee! how to set it on fullscreen?.. I wont to do trashing "AKA tinkering" with your code to achieve it. video about it soon

**Comment by yuv422** [comment]
You can use the `-fs` command line argument to run it in fullscreen mode. :)

**Comment by Askmewho** [comment]
Ohh, I just modified the src hahaha ok!! I will do thst next time. Add the --help menu please

**Comment by Askmewho** [comment]
I get index O, not a compat controller. How I do setup the controller. I judt copy pasted from the list you have to the build folder config file

**Comment by Askmewho** [comment]
here it's https://www.youtube.com/watch?v=ZWtMzBWY9-g&feature=youtu.be

**Comment by Askmewho** [comment]
@yuv422 hope you like the video :)

**Comment by yuv422** [comment]
@Askmewho  I did, thanks :)
