### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Askmewho** [yuv422/cosmo-engine#8]
?

**Comment by jschwartzenberg** [comment]
I guess it should run fine on GNU/Linux. I could run it on Ubuntu 18.04 without problems:
![afbeelding](https://user-images.githubusercontent.com/877112/84560734-ef295200-ad46-11ea-9bb0-2c9213fbe037.png)

I had to install `libsdl2-mixer-dev` and after cloning:
```
mkdir build
cd build
cmake ..
make
```

**Comment by Askmewho** [comment]
Are you thinking on enhancements down the road?

**Comment by yuv422** [comment]
I think thinking about mid-level checkpoints.
Increasing the fps and smoothing the motion.

**Comment by Askmewho** [comment]
Ohh yeah, fps increase should be a must. Thanks, I will let you know if somethings happen bc I am on arm linux.

**Comment by jschwartzenberg** [comment]
Btw. I learned about this engine here: https://github.com/lethal-guitar/RigelEngine/issues/542

I don't know if it makes sense to combine anything. Both engines seem quite complete already and I don't know how big/small the different between the games really were in the end.

**Comment by lethal-guitar** [comment]
@jschwartzenberg thanks for the shout out! I don't think combining makes much sense, since the two code bases have very different architectures.

**Comment by jschwartzenberg** [comment]
Yeah, both are maintained too :) I just didn't see Cosmo-Engine on https://osgameclones.com/ which is where I found RigelEngine, but I submitted it this morning.

**Comment by mnhauke** [comment]
I just made a RPM package for openSUSE
https://build.opensuse.org/package/show/home:mnhauke:games/cosmo-engine
https://build.opensuse.org/package/view_file/home:mnhauke:games/cosmo-engine/cosmo-engine.spec?expand=1

openSUSE users can now use the one-click installer to install the game:
https://software.opensuse.org/package/cosmo-engine?search_term=cosmo-engine
